# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: goconfig
  CURRENT_VERSION:
    sh: sbot get version
  VERSION: '{{ .NEXT_VERSION | default .CURRENT_VERSION }}'

tasks:
  default:
    deps:
      - help
    silent: true

  ci:
    desc: CI task; cleans, run tests, and builds
    deps:
      - gen
      - vale
      - test
      - build

  doctor:
    desc: run doctor.sh to sort out development dependencies
    cmds:
      - ./.tools/doctor.sh

  guard:
    desc: run guard to watch
    cmds:
      - bundle exec guard

  gen:
    desc: run code-generation
    run: once
    cmds:
      - go run ./.tools/version_gen.go {{ .PROJECT_NAME }}
    env:
      VERSION: "{{ .VERSION }}"

  bundle:
    desc: install ruby gems
    run: once
    cmds:
      - bundle --quiet
  
  vale:
    desc: run linting rules against markdown files
    run: once
    cmds:
    - vale README.md CONTRIBUTING.md # we don't valedate CHANGELOG.md as that reflects historical commit summaries
    # TODO: run only when not in GITHUB_ACTIONS

  test:
    desc: run tests
    run: once
    deps:
      - gen
    cmds:
      - go test ./...
    silent: true

  autotest:
    desc: run tests continuously using goconvey's test UI
    deps:
      - gen
    cmds:
      - goconvey
    silent: true

  features:
    desc: run acceptance tests
    deps:
      - bundle
      - gen
      - test
      - build
    cmds:
      - bundle exec cucumber --publish-quiet --tags 'not @wip' --tags 'not @ignore'

  features-wip:
    desc: run wip acceptance tests
    deps:
      - bundle
      - gen
      - test
      - build
    cmds:
      - bundle exec cucumber --publish-quiet --tags '@wip' --tags 'not @ignore'

  build:
    desc: build
    run: once
    deps:
      - gen
      - test
    cmds:
      - go build -o ./bin/goconfig ./cmd/goconfig

  help:
    desc: list targets
    cmds:
      - echo "{{ .PROJECT_NAME}} v{{ .VERSION }}"
      - echo ""
      - task --list
    silent: true

