# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps:
      - help
    silent: true

  test:
    desc: run tests
    cmds:
      - go test ./...
    silent: true

  autotest:
    desc: run tests continuously using goconvey's test UI
    cmds:
      - goconvey
    silent: true

  help:
    desc: list targets
    cmds:
      - task --list
    silent: true

