# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: goconfig
  VERSION:
    sh: sbot get version

tasks:
  default:
    deps:
      - help
    silent: true

  ci:
    desc: CI task; cleans, run tests, and builds
    deps:
      - gen
      - vale
      - test
      - build
    
  doctor:
    desc: run doctor.sh to sort out development dependencies
    cmds:
      - ./.tools/doctor.sh

  gen:
    desc: run code-generation
    cmds:
      - go run ./.tools/version_gen.go {{ .PROJECT_NAME }}
  
  vale:
    desc: run linting rules against markdown files
    cmds:
    - vale README.md # we don't valedate CHANGELOG.md as that reflects historical commit summaries
    # TODO: run only when not in GITHUB_ACTIONS

  test:
    desc: run tests
    deps:
      - gen
    cmds:
      - go test ./...
    silent: true

  autotest:
    desc: run tests continuously using goconvey's test UI
    deps:
      - gen
    cmds:
      - goconvey
    silent: true

  build:
    desc: build
    deps:
      - gen
      - test
    cmds:
      - go build -o ./bin/goconfig ./cmd/goconfig

  help:
    desc: list targets
    cmds:
      - echo "{{ .PROJECT_NAME}} v{{ .VERSION }}"
      - echo ""
      - task --list
    silent: true

